### ISSUE TITLE
getImageFill

### ISSUE THREAD

**Issue by dansleboby** [typpo/quickchart-js#13]
How to user "getImageFill" in dataset with JS api, I it always escape it in url so it not work

thanks

**Comment by typpo** [comment]
Hi @dansleboby, the easiest way right now is to send your whole chart as a string.  For example

```
const config = `{
  type: 'radar',
  data: {
    labels: ['A', 'B', 'C'],
    datasets: [
      {
        backgroundColor: getImageFill('https://cdn.pixabay.com/photo/2017/08/30/01/05/milky-way-2695569__340.jpg'),
        borderColor: 'green',
        borderWidth: 1,
        pointRadius: 0,
        data: [1, 2, 3],
      },
    ],
  },
  options: {
    legend: {
      display: false
    },
    scale: {
      ticks: {
        beginAtZero: true,
      },
      angleLines: {
        display: false
      },
      pointLabels: {
        display: false
      },
    }
  },
}`;

const myChart = new QuickChart();
myChart.setConfig(config);
```

`getImageFill` _should_ be added as a built-in function [here](https://github.com/typpo/quickchart-js#using-built-in-quickchart-functions).  This work is planned.  I will leave this issue open to track this.

**Comment by typpo** [comment]
Support for `QuickChart.getImageFill` has been added in v1.3.0.  You can see an example here  https://github.com/typpo/quickchart-js/blob/master/examples/image_fill.js

**Comment by dansleboby** [comment]
https://github.com/typpo/quickchart-js#using-built-in-quickchart-functions

Dont forget to update the readme 😊

**Comment by typpo** [comment]
Done. Thanks!
