### ISSUE TITLE
Add Support for version/v query param.

### ISSUE THREAD

**Issue by ndelage** [typpo/quickchart-js#15]
This library and the corresponding https://github.com/typpo/chartjs-to-image don't appear to support the `version` query param. Without support for this param I don't think I can use chartjs `v3` with quickchart.

Here's the params list for quickchart: https://quickchart.io/documentation/#parameters

Is there a way to make use of the version param today? It appears this is going to require a code change.

**Comment by typpo** [comment]
I've just added `setVersion` in v1.4.0

You can use it to set the version to 3+

**Comment by ndelage** [comment]
Awesome! Thanks for the quick update!
