### ISSUE TITLE
API Key Implementation

### ISSUE THREAD

**Issue by AndrejHronco** [typpo/quickchart-js#18]
Hi, really enjoying the package.
I noticed that the api key isn't used in the get/post url to quickchart.io so there's no way to use your package with a paid license.

I see where the url params for the `key` need to go but wanted to check in and see why this hasn't been implemented.

Appreciate it

**Comment by typpo** [comment]
Thanks for flagging this!  cf7b1b3251a42eb060405798db7000140777c085 fixes the issue and adds related tests.  The update has been released on npm in version 1.4.2.
