### ISSUE TITLE
How to use quickchart-js with graphviz?

### ISSUE THREAD

**Issue by DanielSWolf** [typpo/quickchart-js#22]
All examples for `quickchart-js` use `type: 'bar'` with a JSON representation of the data. What's the syntax for creating a `QuickChart` object with `type: 'graphviz'`?

**Comment by typpo** [comment]
Hi Daniel, this library doesn't support graphviz URL construction.  The graphviz API is simple enough that I recommend constructing the GET or POST request yourself.  

There's a JS example [here](https://quickchart.io/documentation/graphviz-api/#api-parameters) - happy to provide another example if the way forward is not clear.

**Comment by DanielSWolf** [comment]
This example is exactly what I'd been looking for! Thank you!
