### ISSUE TITLE
import blows up in CRA/Webpack app

### ISSUE THREAD

**Issue by rayhatfield** [typpo/quickchart-js#24]
Standard import doesn't work with webpack in a CRA app.

```js
import QuickChart from 'quickchart-js'
```
Results in an error in the browser:

```
Uncaught TypeError: quickchart_js__WEBPACK_IMPORTED_MODULE_2___default(...) is not a constructor
```

This appears to be due to webpack choosing the `browser` package.json field over `main` or `module`.

One can work around it by explicitly importing the esm build:

```js
import QuickChart from "quickchart-js/build/quickchart.esm.js";
```

This is not my area of expertise. Is the `browser` field still needed?

**Comment by typpo** [comment]
Thanks for the report, Ray.  I'm not sure removing the `browser` field solves the issue.  I'm going to add a note to the readme for now while I look into it more.

**Comment by locbq** [comment]
@typpo I still have the same issue with version 3.0.0

**Comment by typpo** [comment]
@locbq Are you sure you've upgraded correctly?  3.0.0 works fine in a new CRA app:

```bash
npx create-react-app scratch-app
cd scratch-app
npm i --save quickchart-js
```

Replace `src/App.js` with the following:

```js
import QuickChart from 'quickchart-js'

function App() {
  const qc = new QuickChart();
  qc.setConfig({
    type: 'bar',
    data: { labels: ['Hello world', 'Foo bar'], datasets: [{ label: 'Foo', data: [1, 2] }] },
  });
  return (
    <div className="App">
      <img src={qc.getUrl()} />
    </div>
  );
}
```

Here is the entry in `package-lock.json`:
```json
    "quickchart-js": {
      "version": "3.0.0",
      "resolved": "https://registry.npmjs.org/quickchart-js/-/quickchart-js-3.0.0.tgz",
      "integrity": "sha512-jwb5JrL2bGfU/OMkXGvrY/OjveVkzFMzFSRugs+RO35xGQrbJi1s9eC9xuwYI24lMxcgW+bugtYAR3Qhp5M1MA==",
      "requires": {
        "cross-fetch": "^3.1.5",
        "javascript-stringify": "^2.1.0"
      }
    },
```

**Comment by typpo** [comment]
If you're able to share a project with a repro, I'm happy to take a look.  I am unable to reproduce this issue from a clean install of CRA :/
