### ISSUE TITLE
Missing chart.js dependency

### ISSUE THREAD

**Issue by BenSegal855** [typpo/quickchart-js#29]
A type is imported form [chart.js](https://www.npmjs.com/package/chart.js) in [src/index.ts](https://github.com/typpo/quickchart-js/blob/master/src/index.ts#L6) but chart.js is not a dependency listed in the [package.json](https://github.com/typpo/quickchart-js/blob/master/package.json#L29). In projects using typescript, this results in [`QuickChart#setConfig()`](https://github.com/typpo/quickchart-js/blob/master/src/index.ts#L80)'s argument being of type `any` unless chart.js is added as a dependency. 

This screenshot was taken without chart.js installed my my project. As you can see, the parameter has an `any` type.
![Without chart.js installed](https://user-images.githubusercontent.com/34194692/161436448-6fb94842-3678-4320-8f31-f384a39dd9f4.png)

This one was taken after installing chart.js. Here typescript knows what type the parameter should be.
![With chart.js installed](https://user-images.githubusercontent.com/34194692/161436422-7aed4f66-7f11-4a0d-b723-ffa195065a00.png)

**Comment by typpo** [comment]
Hey @BenSegal855, are you sure you installed developer dependencies?  Chart.js types are included under `devDependencies` https://github.com/typpo/quickchart-js/blob/master/package.json#L36.  The actual Chart.js package is not a hard requirement for this project at runtime

**Comment by BenSegal855** [comment]
> are you sure you installed developer dependencies?

I'm not sure what you mean here. Running `npm install quickchart-js` as the readme suggests does not install dev dependencies and thus does not install `@types/chart.js`. If there is more I need to do to use this library with typescript, shouldn't that be in the readme?

**Comment by typpo** [comment]
I agree with you.  The ChartConfiguration type shows up in the declaration file, so it really belongs in `dependencies` instead of `devDependencies`.  There's some discussion of this [here](https://stackoverflow.com/questions/45176661/how-do-i-decide-whether-types-goes-into-dependencies-or-devdependencies)

**Comment by typpo** [comment]
[Published](https://www.npmjs.com/package/quickchart-js) in 3.0.1
