### ISSUE TITLE
`quickchart-js` should upgrade `moment` to 2.29.4

### ISSUE THREAD

**Issue by taschetto** [typpo/quickchart-js#33]
`moment@2.29.2` contains a vulnerability that will cause most security scanners to flag (as it's high).

Details here: https://github.com/advisories/GHSA-wc69-rhjr-hc9g

**Comment by typpo** [comment]
Thanks.  This has been done in 987f87a052252a5da4f562bba0e24b4a8501b8ff

**Comment by typpo** [comment]
The update is published in v3.0.2
