### ISSUE TITLE
How to set a custom domain?

### ISSUE THREAD

**Issue by QuynhVir** [typpo/quickchart-js#34]
If I run a private QuickChart instance, how do I set this client to call that domain instead of quickchart.io

**Comment by typpo** [comment]
Hi @QuynhVir,

In version 3.1.0 the library now supports `setHost` and `setScheme`.  Here's an example usage:

```
const qc = new QuickChart();

qc.setScheme('https');
qc.setHost('example.com');
qc.setConfig({
  type: 'bar',
  data: { labels: ['Hello world', 'Foo bar'], datasets: [{ label: 'Foo', data: [1, 2] }] },
});

console.log(qc.getUrl());
```
