### ISSUE TITLE
Limited to three points only

### ISSUE THREAD

**Issue by Tekkyu** [typpo/quickchart-js#36]
Hello, i'm trying to make a chart but sadly only the first 3 data are being used and the other's data are getting ignored, i end up having only 3 points on my chart.. Here's my code : 
`const myChart = new QuickChart();
            myChart.setConfig({
              type: 'line',
              data: { labels: ['Last ranked games by tekkyu ','Rank : '+graph.data[graph.data.length - 1].currenttierpatched , 'elo: '+stats.data.elo], datasets: [{ label: 'RR change', data: [11,34,48,68,88,94] }] },
            });
            myChart.setWidth(500).setHeight(300).setBackgroundColor('transparent');
          let chart=(myChart.getUrl()); `

and the quickchart.io link generated : [Link](https://quickchart.io/chart?c=%7Btype%3A%27line%27%2Cdata%3A%7Blabels%3A%5B%27Last+ranked+games+by+tekkyu+%27%2C%27Rank+%3A+Iron+3%27%2C%27elo%3A+276%27%5D%2Cdatasets%3A%5B%7Blabel%3A%27RR+change%27%2Cdata%3A%5B11%2C34%2C48%2C68%2C88%2C94%5D%7D%5D%7D%7D&w=500&h=300&bkg=transparent&f=png&v=2.9.4)

I don't see any option with a limit of data numbers being used in the documentation so i'm very confused if anyone could help me out.

thanks

**Comment by typpo** [comment]
Hi Tekkyu,

Your graph is working as constructed.  You only specify 3 labels, so it shows 3 points:

```
{
  type: 'line',
  data: {
    labels: [
      'Last ranked games by tekkyu ',
      'Rank : ' + graph.data[graph.data.length - 1].currenttierpatched,
      'elo: ' + stats.data.elo,
    ],
    datasets: [{ label: 'RR change', data: [11, 34, 48, 68, 88, 94] }],
  },
}
```

I would suggest that you review the Chart.js documentation.  If you want to show everything listed in the "RR change" dataset, you can remove `labels` and maybe move that info to `title`:

```
{
  type: 'line',
  data: {
    datasets: [{ label: 'RR change', data: [11, 34, 48, 68, 88, 94] }],
  },
  options: {
    title: {
      display: true,
      text: [
        'Last ranked games by tekkyu ',
        'Rank : ...' + graph.data[graph.data.length - 1].currenttierpatched,
        'elo: ...' + stats.data.elo,
      ],
    },
  },
}
```
