### ISSUE TITLE
How to include quickchart-js using google app script

### ISSUE THREAD

**Issue by petertalkman** [typpo/quickchart-js#37]
I'm developing something through google apps script and want to create charts by quickchart, how can I include quickchart library ? Thanks

**Comment by typpo** [comment]
HI @petertalkman!  In Google Apps Script, it's probably easiest to construct the QuickChart URL manually.  You don't need quickchart-js for this.

For example:
```js
function GetChartUrl(values) {
  console.log('Values:', values);

  var width = 500;
  var height = 300;
  var backgroundColor = 'white';
  var config = `{
  type: 'bar',
  data: {
    labels: ['Q1', 'Q2', 'Q3', 'Q4'],
    datasets: [{
      label: 'Data',
      data: [${values.join(',')}]
    }]
  }
}
`;
  return `https://quickchart.io/chart?c=${encodeURIComponent(config)}&w=${width}&h=${height}&bkg=${backgroundColor}&devicePixelRatio=1`
}
```

And the formula in Google Sheets:
```
=GetChartUrl(A2:A6)
```
or, to display an image:
```
=IMAGE(GetChartUrl(A$2:A$5))
```

Here's an example sheet that generates a chart URL: https://docs.google.com/spreadsheets/d/1cOjoT4viETplmdTvNOeDKVjwIqZpIr2afMCiK7vgQLY/edit#gid=0
