### ISSUE TITLE
Can't set background to transparent.

### ISSUE THREAD

**Issue by pgsleepy** [typpo/quickchart-js#39]
QuickChart always exports with a white background no matter what.

```js
chart.setConfig({
                      type: 'line',
                      data: {
                        datasets: [{
                          data: duelsArrayMMRNew,
                          fill: false,
                          borderColor: QuickChart.getGradientFillHelper('vertical', ['#eb3639', '#a336eb', '#36a2eb']),
                          borderWidth: 3,
                          pointRadius: 1,
                        }]
                      },
                      options: {
                        legend: {
                          display: false
                        },
                        scales: {
                        xAxes: [{
                          display: false,
                          gridLines: {
                            display: false,
                          },
                        }],
                        yAxes: [{
                          display: false,
                          gridLines: {
                            display: false,
                          },
                        }]
                      },
                      }
                    });
```

This outputs [this URL](https://quickchart.io/chart?c=%7Btype%3A%27line%27%2Cdata%3A%7Bdatasets%3A%5B%7Bdata%3A%5B1671715255%2C1672763448%5D%2Cfill%3Afalse%2CborderColor%3AgetGradientFillHelper%28%22vertical%22%2C+%5B%22%23eb3639%22%2C%22%23a336eb%22%2C%22%2336a2eb%22%5D%2C+undefined%29%2CborderWidth%3A3%2CpointRadius%3A1%2Cbackground%3A%270%27%7D%5D%7D%2Coptions%3A%7Blegend%3A%7Bdisplay%3Afalse%7D%2Cscales%3A%7BxAxes%3A%5B%7Bdisplay%3Afalse%2CgridLines%3A%7Bdisplay%3Afalse%7D%7D%5D%2CyAxes%3A%5B%7Bdisplay%3Afalse%2CgridLines%3A%7Bdisplay%3Afalse%7D%7D%5D%7D%7D%7D&w=253&h=108&bkg=%23ffffff&f=png&v=2) and saving it also shows white background.

**Comment by typpo** [comment]
Can you show me how you're setting the background color?  You should be using `config.setBackgroundColor` ([link](https://github.com/typpo/quickchart-js#setbackgroundcolorcolor-string))

**Comment by pgsleepy** [comment]
> Can you show me how you're setting the background color? You should be using `config.setBackgroundColor` ([link](https://github.com/typpo/quickchart-js#setbackgroundcolorcolor-string))

I'm not trying to set the background color, I want to have it as default: transparent.
The API documentation shows that the default should always be transparent.

**Comment by pgsleepy** [comment]
I see that the documentation through that link says that the default is white.
The [other documentation](https://quickchart.io/documentation/reference/colors-and-backgrounds/) refers to it as transparent, sorry about that.

I just tried to add `.setBackgroundColor('transparent')` to my chart, which results it into being

```js
                    chart.setConfig({
                      type: 'line',
                      data: {
                        datasets: [{
                          data: duelsArrayMMRNew,
                          fill: false,
                          borderColor: QuickChart.getGradientFillHelper('vertical', ['#eb3639', '#a336eb', '#36a2eb']),
                          borderWidth: 3,
                          pointRadius: 1,
                        }]
                      },
                      options: {
                        legend: {
                          display: false
                        },
                        scales: {
                        xAxes: [{
                          display: false,
                          gridLines: {
                            display: false,
                          },
                        }],
                        yAxes: [{
                          display: false,
                          gridLines: {
                            display: false,
                          },
                        }]
                      },
                      }
                    });
                    chart.setBackgroundColor('transparent')
                    ```

But this still results in a white background.

**Comment by pgsleepy** [comment]
As a matter of fact, just tried to do .setBackgroundColor('#0febc2'); to see if it worked or not, but even that doesn't work.

**Comment by typpo** [comment]
Can you share the URL that is generated, and check the version of `quickchart-js`?  That may give us a hint.

You might also want to double check whatever else you're doing in the project.  A minimal example shows that `setBackgroundColor` is working fine: https://replit.com/@trynafunction/quickchart-js-background-color#index.js

**Comment by pgsleepy** [comment]
As opposed to the first time I sent the URL, now after I've added .setBackgroundColor('transparent') it properly shows on [the new URL](https://quickchart.io/chart?c=%7Btype%3A%27line%27%2Cdata%3A%7Bdatasets%3A%5B%7Bdata%3A%5B1671715255%2C1672763448%5D%2Cfill%3Afalse%2CborderColor%3AgetGradientFillHelper%28"vertical"%2C+%5B"%23eb3639"%2C"%23a336eb"%2C"%2336a2eb"%5D%2C+undefined%29%2CborderWidth%3A3%2CpointRadius%3A1%2CbackgroundColor%3A%27%27%7D%5D%7D%2Coptions%3A%7Blegend%3A%7Bdisplay%3Afalse%7D%2Cscales%3A%7BxAxes%3A%5B%7Bdisplay%3Afalse%2CgridLines%3A%7Bdisplay%3Afalse%7D%7D%5D%2CyAxes%3A%5B%7Bdisplay%3Afalse%2CgridLines%3A%7Bdisplay%3Afalse%7D%7D%5D%7D%7D%7D&w=253&h=108&bkg=rgba%280%2C+140%2C+255%2C+0%29&f=png&v=2)
But it still doesn't show transparent but it still doesn't show transparent for the saved file which is being saved through 
```js
await chart.toFile(`/temp/${API.playerName}_duels.png`);
```

The version I'm using is quickchart-js@3.1.1

**Comment by typpo** [comment]
The example repl above is also writing fine with `toFile`.  Have a look at that example and/or you may want to double-check your local setup.

**Comment by pgsleepy** [comment]
Not gonna lie, hate the player dont hate the game but I hate coding sometimes lol
My previous comment stated

> ```js
> await chart.toFile(`/temp/${API.playerName}_duels.png`);
> ```

Which doesn't include the dot right before the /temp folder...
So basically the first generation that I had with the toFile was succesful, and somehow I removed the dot at some point and it didn't occur to me that I was constantly being shown the first generation...

**Comment by pgsleepy** [comment]
Not gonna lie, hate the player dont hate the game but I hate coding sometimes lol
My previous comment stated

> ```js
> await chart.toFile(`/temp/${API.playerName}_duels.png`);
> ```

Which doesn't include the dot right before the /temp folder...
So basically the first generation that I had with the toFile was succesful, and somehow I removed the dot at some point and it didn't occur to me that I was constantly being shown the first generation...

Thank you for your help!

**Comment by typpo** [comment]
It happens!  Glad you figured it out.

Also thanks for pointing out the inconsistency around the default background color.  That is something we can fix in the next release.
