### ISSUE TITLE
Updating the npm package with the latest security fix

### ISSUE THREAD

**Issue by adheeshfordev** [typpo/quickchart-js#5]
Hey, 

I just wanted to know if there will there be an update to the npm package with the latest security fix involving the upgrade to a newer version of axios? 

I have been using the quickchart-js npm package. Is there an alternative that can be used on my repository if there is no plan to update the npm package?

**Comment by typpo** [comment]
Hi @adheeshfordev, a new package has been released: v1.0.6 ([npm](https://www.npmjs.com/package/quickchart-js))

**Comment by adheeshfordev** [comment]
Hey @typpo, thank you very much for this.
