### ISSUE TITLE
TypeError: myChart.setConfig is not a function

### ISSUE THREAD

**Issue by adarsh-kh4u** [typpo/quickchart-js#6]
Trying to use chart in Apps Script and getting this error. Below is my code.
```
const myChart = new QuickChart();
myChart.setConfig({
    type: 'bar',
    data: { labels: ['Hello world', 'Foo bar'], datasets: [{ label: 'Foo', data: [1, 2] }] },
  })
  .setWidth(800)
  .setHeight(400)
  .setBackgroundColor('transparent');
```

**Comment by typpo** [comment]
Are you requiring `quickchart-js`?  I'm not aware that Apps Script has npm module support.

You can just construct your own URLs by appending [API parameters](https://quickchart.io/documentation/#parameters) to a URL.  For example:

```
const baseUrl = 'https://quickchart.io/chart?width=800&height=400&bkg=transparent&c=';
const url = baseUrl + encodeURIComponent(JSON.stringify({
    type: 'bar',
    data: { labels: ['Hello world', 'Foo bar'], datasets: [{ label: 'Foo', data: [1, 2] }] },
}));
console.log(url)
```

**Comment by adarsh-kh4u** [comment]
I used require to load `quickchart-js`. I tried to create graph using API also. But problem with constructed url is that the data label formatter is not working. I'm trying to hide labels if they are zero. Below is my formatter.

```
formatter: (value, ctx) => {
          if (value > 0)
            return value;
          else
            return ""
        }
```

**Comment by typpo** [comment]
If you are using the raw API with functions like that, make sure you serialize `chart` as a string rather than a Javascript function.  See [this documentation](https://quickchart.io/documentation/#js-functions) for examples.
